### ISSUE TITLE
pretextview takes 100% cpu usage even when not in active use

### ISSUE THREAD

**Issue by wheaton5** [wtsi-hpag/PretextView#2]
Perhaps you can have some callbacks that wake it up when it needs to respond to some input. It shouldn't need to use 100% cpu just to display a static image. I only realized this because my mac battery was draining (I have the lowest tier power charger) and I looked at my activity monitor and it showed pretextview at 100% cpu usage.

**Comment by EdHarry** [comment]
Sorry about that.
https://github.com/wtsi-hpag/PretextView/releases/tag/0.1.6
This new release should fix the problem.

**Comment by wheaton5** [comment]
thanks
