### ISSUE TITLE
0.1.6 release (MacOS)

### ISSUE THREAD

**Issue by epaule** [wtsi-hpag/PretextView#3]
for the 0.1.6 MacOS release:

would it be possible that the version numbers in the mac app (in Info.plist) be in sync with the github release number (as in 0.1.6)? Currently it shows as 0.01, as that is what is in the CFBundleShortVersionString

similar, could you create the directories from scratch (or touch them) during the build, as the app info shows "created Friday 1, November 2019", even if the actual binaries are newer inside.

**Comment by EdHarry** [comment]
Sure, no problem. Thanks for pointing these issues out.

**Comment by EdHarry** [comment]
I've updated the Mac app under the 0.1.6 release.
