### ISSUE TITLE
usage problem

### ISSUE THREAD

**Issue by zhoudreames** [wtsi-hpag/PretextView#4]
this is my hic plot.but i want to add the scaffold name in the top of the plot. then ,there are many no off-diagonal signals,could  you tell how to fix it ? thanks

**Comment by zhoudreames** [comment]
![WechatIMG314](https://user-images.githubusercontent.com/54714639/125167708-73613980-e1d4-11eb-8dc1-f9557ef90c19.png)

**Comment by zhoudreames** [comment]
@EdHarry i am so sorry disturb you ,could you help me ? thanks

**Comment by EdHarry** [comment]
Hi,
You can access the UI menu with the ‘u’ key, from there you can turn name labels on. You can also try changing the colour map and/or adjusting the gamma correction.
