### ISSUE TITLE
how  to save hic plot ？

### ISSUE THREAD

**Issue by zhoudreames** [wtsi-hpag/PretextView#6]
![image](https://user-images.githubusercontent.com/54714639/134317024-d225f621-5ce2-44fe-9566-96774a6d6f63.png)
i want  to save the whole picture for hic resulting ,but I don't how to save it ,could you help me?

**Comment by zhoudreames** [comment]
my computer is mac Os system

**Comment by EdHarry** [comment]
Hi,
I'm afraid that there's no inbuilt method for generating an image.
However, you can take a screenshot (shift-command-4 or shift-command-4-space, https://support.apple.com/en-gb/HT201361)
If you haven't made any edits to the map you could also use [PretextSnapshot](https://github.com/wtsi-hpag/PretextSnapshot)

**Comment by zhoudreames** [comment]
thanks
