### ISSUE TITLE
New feature requests.

### ISSUE THREAD

**Issue by EdHarry** [wtsi-hpag/PretextView#7]
# Requests
Feature requests made by Sanger GRIT team on 18/11/2021.

## Scaffold Painting
* Paint all option.
* Paint region option, i.e. select a start and an end.

## Editing
* Ability to tag regions with extra meta-data (e.g. haplotig).
    * Ability to sort / rearrange map based on meta-data tags.
    * Ability to export meta-data in AGP output.
    * Option to auto-tag painted sequences.
    * Default tags:
        * Haplotig
        * Unloc
        * X
        * Y
        * Z
        * W 
* Ability to edit non-contiguous regions.
* Ability to import AGP.
* Option to preserve sequence order in AGP output.

## UI
* More accurate position info on tooltip.
* Scaffold lookup menu.

## Rendering
* Increased resolution.

# Estimated difficulty / priority queue
## Easy, ~1 week turnaround time
* Paint all.
* Paint regions.
* More accurate tooltip.
* Auto-tag option.
* New default tags.
* AGP sequence preservation option. 

## Medium, ~3-4 weeks turnaround time
* Meta-data tags, sorting based on tags, exporting meta-data.
* Non-contiguous editing.
* Scaffold lookup.

## Hard, no estimate on turnaround, experimentation required
* Resolution increase.

**Comment by atracey99** [comment]
Could we have a search box to look up scaffold names please?  Looking up via sequence list can be very inefficient with long potentially unsorted lists

**Comment by EdHarry** [comment]
> Could we have a search box to look up scaffold names please? Looking up via sequence list can be very inefficient with long potentially unsorted lists

Sure, I should be able to add something like that.

**Comment by EdHarry** [comment]
Development release: [0.2.5-dev-0](https://github.com/wtsi-hpag/PretextView/releases/tag/0.2.5-dev-0)

Implemented features:
- More scaffold painting options.
- More accurate tooltip.
- Scaffold lookup.
- Meta data tags.

Any feedback will be appreciated.

**Comment by jeramiahsmith** [comment]
HI,  I have been giving this a try and am loving the interface. One thing I am wondering is if it would somehow be possible to import an external AGP file to aid in initial ordering of scaffolds.  Perhaps such a feature already exists though?

**Comment by EdHarry** [comment]
> HI, I have been giving this a try and am loving the interface. One thing I am wondering is if it would somehow be possible to import an external AGP file to aid in initial ordering of scaffolds. Perhaps such a feature already exists though?

I think this should be possible, I'll see if I can get something like this implemented in the next devel release.

**Comment by EdHarry** [comment]
Development release: [0.2.5-dev-1](https://github.com/wtsi-hpag/PretextView/releases/tag/0.2.5-dev-1)

New features:
- More default tags.
- Painted sequences auto-tagged in AGP output.
- Higher resolution support (experimental). See [PretextMap branch](https://github.com/wtsi-hpag/PretextMap/tree/inc_resolution) with high resolution option.

**Comment by EdHarry** [comment]
Development release: [0.2.5-dev-2](https://github.com/wtsi-hpag/PretextView/releases/tag/0.2.5-dev-2)

New features:
- Option to preserve sequence order in AGP output.
- Option to display embedded graph labels.

Note: Save-states only compatible with previous version (0.2.5-dev-1).

**Comment by EdHarry** [comment]
[Full 0.2.5 release](https://github.com/wtsi-hpag/PretextView/releases/tag/0.2.5)

Unfortunately some requested features weren't able to make this release:
* Non-contiguous editing
* AGP input

This thread will close for now, but may reopen, pending future development work.
